//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostnameService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Name
    {
        public int ID { get; set; }
        public string GeneratedName { get; set; }
        public string SName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> TypeeID { get; set; }
        public Nullable<int> PlatformID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> Number { get; set; }
        public string HostName { get; set; }
        public string Comment { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Platformm Platformm { get; set; }
        public virtual Project Project { get; set; }
        public virtual Rolee Rolee { get; set; }
        public virtual Typee Typee { get; set; }
    }
}
