//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamingService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueryLog
    {
        public int ID { get; set; }
        public string QueryDatabaseName { get; set; }
        public string QueryString { get; set; }
        public Nullable<System.DateTime> QueryDate { get; set; }
    }
}
